- Makefile
At least on some local tests, I could get this the release notes to build with this patch
> Build: expand entities - helps with new libxml that became stricter

- xml/release-notes.xml
Recreating the live images is not possible without much effort, so we should warn the users
> Warning about no active firewall after install from live cd

- xml/release-notes.xml
The `hawk` package is dropped from Leap 42.2 and replaced by the `hawk2` package.
> Add note on hawk to hawk2 transition

- xml/release-notes.xml
As requested in http://bugzilla.suse.com/show_bug.cgi?id=1006586, this is a first integration of ntoes regarding KDE PIM in Leap 42.2. I'm not sure it's the right section, but skimming through the document, I could not find anything that would fit.
P.S.: First time doing DocBook, bear that in mind.
> Add notes to KDE PIM

- xml/release-notes.xml
- X.org synaptics driver pulled in by default
- Global menu bar backport
- KDE PIM 4.x dropped
- Baloo only indexes file names by default
> Add various KDE-related sections

- .gitignore
- Makefile
Not just better (hopefully) than xml2po but also more maintained and
Python-3-based (instead of 2)
Can't use its:translate tag yet, since neither DocBook nor GeekoDoc
allow for it by default
> Use ITS Tool

- xml/release-notes.xml
I remove &thisflavor; because of "openSUSE Leap openSUSE Leap 15.0" in Release Notes.
&thisversion; is giving the correct outout "openSUSE Leap 15.0".
> "remove &thisflovor;  because of written twice openSUSE Leap" (*)

- xml/release-notes.xml
Every Leap version has got a separate feature page in the Wiki. 15.1 will have an own one, too.
Therefore, I have changed the version number to 15.1 in the URL.
> Change version number for Feature Wiki page

- xml/release-notes.xml
There is a grammar error. The German "weder-noch" is translated "neither-nor" instead of "not-nor".
> grammar error: neither nor

- xml/release-notes.xml
python-pyside and python-pyside-tool are "both" removed. A "and" was missing for correct grammar.
> Missing "and" between 2 packages

- xml/release-notes.xml
* gcompris (old gtk version) dropped replaced by gcompris-qt package
To be in paar with the delete sr#814299 & the new submission sr#815300 & sr#815301
> Add note about gcompris (old gtk version) dropped

- xml/release-notes.xml
- unsigned modules cannot be loaded; they are not just considered tainted!
- improve documentation about NVIDIA graphics; updated openSUSE WIKI URL
for this
> Corrected Secure Boot section

- xml/release-notes.xml
Detail about the kernel split in Leap 15.3. Old kernel was essentially replaced by three packages.
> Leap 15.3 kernel packaging unification

- xml/release-notes.xml
There were wrong two links to Startup Book in Documentation.
> Fixed links to Docs: Startup Book

- xml/release-notes.xml
Package is no longer built on ppc64le, therefore removing from media.
> Removal of digikam from ppc64le

- xml/release-notes.xml
msgpack was replaced by msgpack-c and msgpack-cxx
https://build.opensuse.org/request/show/1030104
> replacement of msgpack

- xml/release-notes.xml
see https://build.opensuse.org/request/show/1058844
> add nodejs-electron to removed packages list

- xml/release-notes.xml
ibus is not started automatically by KDE Plasma (boo#1211977). So user who use ibus to input language such us Japanese can not input it.
I want to write it and workaround.
Thanks.
> Add note ibus is not started automatically by KDE Plasma (boo#1211977)

- xml/release-notes.xml
* Superseeded by https://en.opensuse.org/SDB:NVIDIA_SUSE_Prime according to this comment https://bugzilla.opensuse.org/show_bug.cgi?id=1159116#c3
> Remove Bumblebee packages

- xml/release-notes.xml
Not all pkgs from the project were removed as dkms and VirtualGL are still used by other pkgs.
> Correction of removed pkgs from bumlebee effort

- README.md
Adjust link to doc.opensuse.org as described in #149
> Adjust link to doc.opensuse.org
