README.md, tools/bin/update_release_notes, tools/etc/releasenotes, www/index.html, www/robots.txt
this request includes the tools and web page for the openSUSE release notes that are available below 
https://doc.opensuse.org/release-notes/
=> Adding release-notes online stuff

www/index.html
=> Fix Leap 42.1 release notes URL

xml/release-notes.xml
I found some minor errors in the English.
=> Fix errors in the English

xml/release-notes.xml
Release note for SR#417184 and SR#417891
=> moinmoin-wiki replaces python-moin

xml/release-notes.xml
See https://build.opensuse.org/request/show/431550
=> Document dropping of pkg labplot in favour of labplot-kf5.

www/index.html, xml/release-notes.xml
https://bugzilla.opensuse.org/show_bug.cgi?id=1008437
=> More consistently use bugzilla.opensuse.org

xml/release-notes.xml
=> Mention dropped plasma5-mediacenter

xml/release-notes.xml
https://bugzilla.opensuse.org/show_bug.cgi?id=1089061#c18
=> boo#1089061

xml/release-notes.xml
The subject "you" was missing in the if sentence.
=> Grammar Error

xml/release-notes.xml
Slapi nis has been requested for removal in https://build.opensuse.org/request/show/760508
=> Document removal of slapi-nis 

xml/release-notes.xml
https://build.opensuse.org/request/show/766866
=> python-django_compressor renamed to python-django-compressor

xml/release-notes.xml
Current WIP, this is an important change that needs to be visible.
=> Add notes regarding bsc#173158 - CONFIG_MODULE_SIG

xml/release-notes.xml
Some fixups for Lubos' PR #96.
=> Improved section about CONFIG_MODULE_SIG=y

xml/release-notes.xml
https://build.opensuse.org/request/show/816034
Signed-off-by: Olaf Hering <olaf@aepfle.de>
=> Mention removal of lilo.rpm

xml/release-notes.xml
Write about boo#1177545 in 15.3 release note since users need manual config migration.
=> boo#1177545 IBus layout name change

xml/release-notes.xml
* Requested to be removed in 15.4
https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/message/Z5MVF7JBNQXKGNPT4TVML62NGHJSGWSI/
=> EOL of midori

xml/release-notes.xml
=> Document our handling of boo#1186593

xml/release-notes.xml
repo-sle-update -> repo-update for OSS updates
=> Correct name for the repo-update fixes Issue #111

xml/release-notes.xml
https://code.opensuse.org/leap/features/issue/15
=> drop of python 2 jsc#SLE-16747

xml/release-notes.xml
More information in https://code.opensuse.org/leap/features/issue/66
=> removal of could-init-vmware-guestinfo code-o-o#66

xml/release-notes.xml
Document a kernel change affecting iotop.
For details see boo#1200669
https://bugzilla.opensuse.org/show_bug.cgi?id=1200669
=> Add general note about iotop

xml/release-notes.xml
* I'm not sure if this is the right section, but we couldn't find anything better
=> python-podman changed upstream project

release-notes.pot
Changed text to reflect 15.4 is EOL. please pull
=> 15.4 is EOL not 15.6

release-notes.pot
Another iteration of 15.6 where it should read 15.4
=> Another iteration of 15.6 where it should read 15.4

xml/release-notes.xml
I removed ibus issue. This issue was fixed already. Thank you.
=> remove ibus issue
